name: sangeet
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter_native_splash: ^2.4.7
  shared_preferences: ^2.1.0
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.4
  flutter_color_extractor: ^1.0.0
  palette_generator: ^0.3.3
  just_audio: ^0.10.5
  audio_service: ^0.18.15
  rxdart: ^0.28.0
  audio_session: ^0.2.2
  http: ^1.1.0
  provider: ^6.1.1
  firebase_core: ^3.4.1
  firebase_auth: ^5.7.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.0


  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  local_auth: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_native_splash:
  color: "#E6D690"
  image: assets/images/Gemini_Generated_Image_ll6zfull6zfull6z.png
  android: true
  ios: true
  web: false

  android_12:
    color: "#282327"
    image: assets/images/Gemini_Generated_Image_ll6zfull6zfull6z.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: Merry
      fonts:
        - asset: assets/fonts/Merriweather-VariableFont_opsz,wdth,wght.ttf
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/Merriweather-Italic-VariableFont_opsz,wdth,wght.ttf
          style: italic
